package com.example.tachiyomi_clone.utils

object Constant {

    const val API_KEY = "api_key"
    const val SHARED_PREFS_FILENAME = "secret_shared_prefs"
    const val BASE_URL = "https://www.nettruyenup.com/"
    const val SCROLL_THRESHOLD = 31
    val genreListUrl = listOf(
        "action-95",
        "truong-thanh",
        "adventure",
        "anime",
        "chuyen-sinh-2131",
        "comedy-99",
        "comic",
        "cooking",
        "co-dai-207",
        "doujinshi",
        "drama-103",
        "dam-my",
        "ecchi",
        "fantasy-1050",
        "gender-bender-106",
        "harem-107",
        "historical",
        "horror",
        "josei",
        "live-action",
        "manga-112",
        "manhua",
        "manhwa-11400",
        "martial-arts",
        "mature",
        "mecha-117",
        "mystery",
        "ngon-tinh",
        "one-shot",
        "psychological",
        "romance-121",
        "school-life",
        "sci-fi",
        "seinen",
        "shoujo",
        "shoujo-ai-126",
        "shounen-127",
        "shounen-ai",
        "slice-of-life",
        "smut",
        "soft-yaoi",
        "soft-yuri",
        "sports",
        "supernatural",
        "tap-chi-truyen-tranh",
        "thieu-nhi",
        "tragedy-136",
        "trinh-tham",
        "truyen-scan",
        "truyen-mau-214",
        "viet-nam",
        "webtoon",
        "xuyen-khong-205",
        "16",
    )
}